/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadorajava;

//import javax.script.ScriptEngine;

import javax.swing.JLabel;



//import javax.script.ScriptEngineManager;
//import javax.script.ScriptException;

public class calculadora extends javax.swing.JFrame {

    //private int num2;
    //ScriptEngineManager sem = new ScriptEngineManager();
    //ScriptEngine se = sem.getEngineByName("JavaScript");
    //private int num1;
    //private String signo;
    
    public String primernumero;
    public String segundonumero;
    public String operador;

    
    public calculadora() {
        initComponents();
        setLocationRelativeTo(null); // App starting position:
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();
        txtOperacion = new javax.swing.JLabel();
        txtOperacionArriba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(55, 62, 71));
        jButton9.setText("9");
        jButton9.setAlignmentY(0.0F);
        jButton9.setFocusPainted(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setIconTextGap(0);
        jButton9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton9.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, 50));

        jButtonDivide.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButtonDivide.setForeground(new java.awt.Color(55, 62, 71));
        jButtonDivide.setText("/");
        jButtonDivide.setAlignmentY(0.0F);
        jButtonDivide.setFocusPainted(false);
        jButtonDivide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDivide.setIconTextGap(0);
        jButtonDivide.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonDivide.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonDivide.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 50, 50));

        jButtonMultiply.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButtonMultiply.setForeground(new java.awt.Color(55, 62, 71));
        jButtonMultiply.setText("*");
        jButtonMultiply.setAlignmentY(0.0F);
        jButtonMultiply.setFocusPainted(false);
        jButtonMultiply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMultiply.setIconTextGap(0);
        jButtonMultiply.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonMultiply.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonMultiply.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jButtonMinus.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButtonMinus.setForeground(new java.awt.Color(55, 62, 71));
        jButtonMinus.setText("-");
        jButtonMinus.setAlignmentY(0.0F);
        jButtonMinus.setFocusPainted(false);
        jButtonMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMinus.setIconTextGap(0);
        jButtonMinus.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonMinus.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonMinus.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 50, 130));

        jButtonPlus.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButtonPlus.setForeground(new java.awt.Color(55, 62, 71));
        jButtonPlus.setText("+");
        jButtonPlus.setAlignmentY(0.0F);
        jButtonPlus.setFocusPainted(false);
        jButtonPlus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPlus.setIconTextGap(0);
        jButtonPlus.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonPlus.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonPlus.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 50, 130));

        jButtonEqual.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButtonEqual.setForeground(new java.awt.Color(55, 62, 71));
        jButtonEqual.setText("=");
        jButtonEqual.setAlignmentY(0.0F);
        jButtonEqual.setFocusPainted(false);
        jButtonEqual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEqual.setIconTextGap(0);
        jButtonEqual.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonEqual.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonEqual.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, 50));

        jButtonClear.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(55, 62, 71));
        jButtonClear.setText("C");
        jButtonClear.setAlignmentY(0.0F);
        jButtonClear.setFocusPainted(false);
        jButtonClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClear.setIconTextGap(0);
        jButtonClear.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonClear.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonClear.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jButton7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(55, 62, 71));
        jButton7.setText("7");
        jButton7.setAlignmentY(0.0F);
        jButton7.setFocusPainted(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setIconTextGap(0);
        jButton7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 50));

        jButton8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(55, 62, 71));
        jButton8.setText("8");
        jButton8.setAlignmentY(0.0F);
        jButton8.setFocusPainted(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setIconTextGap(0);
        jButton8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(55, 62, 71));
        jButton4.setText("4");
        jButton4.setAlignmentY(0.0F);
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setIconTextGap(0);
        jButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 50));

        jButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(55, 62, 71));
        jButton5.setText("5");
        jButton5.setAlignmentY(0.0F);
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setIconTextGap(0);
        jButton5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 50, 50));

        jButton6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(55, 62, 71));
        jButton6.setText("6");
        jButton6.setAlignmentY(0.0F);
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setIconTextGap(0);
        jButton6.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 50));

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(55, 62, 71));
        jButton1.setText("1");
        jButton1.setAlignmentY(0.0F);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(0);
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 50));

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(55, 62, 71));
        jButton2.setText("2");
        jButton2.setAlignmentY(0.0F);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(0);
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 50, 50));

        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(55, 62, 71));
        jButton3.setText("3");
        jButton3.setAlignmentY(0.0F);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setIconTextGap(0);
        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 50, 50));

        jButton0.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton0.setForeground(new java.awt.Color(55, 62, 71));
        jButton0.setText("0");
        jButton0.setAlignmentY(0.0F);
        jButton0.setFocusPainted(false);
        jButton0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton0.setIconTextGap(0);
        jButton0.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton0.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton0.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 50));

        jButton20.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton20.setForeground(new java.awt.Color(55, 62, 71));
        jButton20.setText(".");
        jButton20.setAlignmentY(0.0F);
        jButton20.setFocusPainted(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setIconTextGap(0);
        jButton20.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton20.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton20.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 340, 404));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        txtResultado.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(55, 62, 71));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtResultado.setText("200");

        txtOperacion.setBackground(new java.awt.Color(204, 255, 204));
        txtOperacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(55, 62, 71));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOperacion.setText("2*100");

        txtOperacionArriba.setBackground(new java.awt.Color(204, 255, 204));
        txtOperacionArriba.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtOperacionArriba.setForeground(new java.awt.Color(55, 62, 71));
        txtOperacionArriba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOperacionArriba.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOperacionArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(txtOperacionArriba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //addNumber("9");
        this.txtOperacion.setText(this.txtOperacion.getText()+"9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        //addNumber("/");
        this.primernumero=this.txtOperacion.getText();
        this.operador= "/";
        this.txtOperacion.setText("");
        this.txtOperacionArriba.setText(primernumero + operador);
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        //addNumber("*");
        this.primernumero=this.txtOperacion.getText();
        this.operador= "*";
        this.txtOperacion.setText("");
        this.txtOperacionArriba.setText(primernumero + operador);
    }//GEN-LAST:event_jButtonMultiplyActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        //addNumber("-");
        this.primernumero=this.txtOperacion.getText();
        this.operador= "-";
        this.txtOperacion.setText("");
        this.txtOperacionArriba.setText(primernumero + operador);
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed

        this.primernumero=this.txtOperacion.getText();
        this.operador= "+";
        this.txtOperacion.setText("");
        this.txtOperacionArriba.setText(primernumero + operador);        
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
       this.segundonumero=this.txtOperacion.getText();
       
       switch (this.operador) {
           case "+":
               Float numero1 = Float.parseFloat(primernumero);
               Float numero2 = Float.parseFloat(segundonumero);
               this.txtResultado.setText(sincero(numero1+numero2));
               break;
           case "-":
               Float numero3 = Float.parseFloat(primernumero);
               Float numero4 = Float.parseFloat(segundonumero);
               this.txtResultado.setText(sincero(numero3-numero4));
               break;
           case "*":
               Float numero5 = Float.parseFloat(primernumero);
               Float numero6 = Float.parseFloat(segundonumero);
               this.txtResultado.setText(sincero(numero5*numero6));
               break;
           case "/":
               Float numero7 = Float.parseFloat(primernumero);
               Float numero8 = Float.parseFloat(segundonumero);
               if(numero8==0) {this.txtResultado.setText("Error");}
               else {
               this.txtResultado.setText(sincero(numero7/numero8));
               break;}               
       }
        
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
       txtResultado.setText("");
       txtOperacion.setText("");
       txtOperacionArriba.setText(""); 
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //addNumber("7");
        this.txtOperacion.setText(this.txtOperacion.getText()+"7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //addNumber("8");
        this.txtOperacion.setText(this.txtOperacion.getText()+"8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //addNumber("4");
        this.txtOperacion.setText(this.txtOperacion.getText()+"4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //addNumber("5");
        this.txtOperacion.setText(this.txtOperacion.getText()+"5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //addNumber("6");
        this.txtOperacion.setText(this.txtOperacion.getText()+"6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //addNumber("1");
        this.txtOperacion.setText(this.txtOperacion.getText()+"1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //addNumber("2");
        this.txtOperacion.setText(this.txtOperacion.getText()+"2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //addNumber("3");
        this.txtOperacion.setText(this.txtOperacion.getText()+"3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        //addNumber("0");
        this.txtOperacion.setText(this.txtOperacion.getText()+"0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code heree:
        if(!(this.txtOperacion.getText().contains("."))){
            this.txtOperacion.setText(this.txtOperacion.getText()+".");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    
    //Si despues del punto tiene 0, lo dejo entero
    public String sincero(float resultado){
        String retorno="";
        retorno=Float.toString(resultado);
        if (resultado%1==0) {
            retorno=retorno.substring(0, retorno.length()-2);
        }
        return retorno;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }
    
    //public void addNumber(String digito) {
    //    txtOperacion.setText(txtOperacion.getText()+ digito);
    //}
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtOperacionArriba;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables

    private int parseInt(JLabel txtOperacion) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
